### ISSUE TITLE
Slack Webhook 연동하여 Error 로그 기록

### ISSUE THREAD

**Issue by PgmJun** [gosopt-LionHeart/LionHeart-Server#1]
## Description 📝
슬랙의 Webhook 연동하여 500 Internal Server Error 발생 시,
슬랙 서버_error-log 채널에 로그 기록

## To-Do ☑️
- [x] slackAlert 브랜치 생성
- [x] 라이온하트 슬랙에 error-log 채널 개설
- [x] error-log 채널과 프로젝트 연결
- [ ] develop 브랜치로 Merge
