### ISSUE TITLE
ChallengePopupType 제거

### ISSUE THREAD

**Issue by PgmJun** [gosopt-LionHeart/LionHeart-Server#65]
## Description 📝
<img width="570" alt="스크린샷 2023-07-20 오후 3 59 51" src="https://github.com/gosopt-LionHeart/LionHeart-Server/assets/84304802/20ebe758-ce23-4a44-a06c-50579c4ebd54">

챌린지 팝업이 없어지고, 유저 가입일로 부터 챌린지 일수를 체크하고 있어서
챌린지 팝업 관련 코드를 제거해도 될 것 같습니다!

## To-Do ☑️
- [x] Challenge 엔티티에서 ChallengePopupType popup 필드 제거
- [x] ChallengePopupType 관련 로직 제거
- [x] schema.sql 수정
- [ ] 배포서버 DB에 수정된 컬럼 반영하기
- [x] ERD Cloud에 변경된 컬럼 반영하기

**Comment by PgmJun** [comment]
alter table CHALLENGE drop column POPUP;

POPUP 컬럼 드랍 ddl입니다
